### ISSUE TITLE
Errors with velocity

### ISSUE THREAD

**Issue by FuchsFuchs1** [DaniFoldi/ProtoGUI#120]
Wenn using this plugin i get errors. Im using velocity.

java.lang.IllegalArgumentException: plugin is not registered
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
    at com.velocitypowered.proxy.scheduler.VelocityScheduler.buildTask(VelocityScheduler.java:70) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
    at com.danifoldi.protogui.platform.velocity.ProtoGui$5.setup(ProtoGui.java:384) ~[?:?]
    at com.danifoldi.protogui.main.ProtoGuiLoader.load(ProtoGuiLoader.java:107) ~[?:?]
    at com.danifoldi.protogui.platform.velocity.ProtoGui.onShutdown(ProtoGui.java:105) ~[?:?]
    at com.danifoldi.protogui.platform.velocity.Lmbda$23.execute(Unknown Source) ~[?:?]
    at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
    at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
    at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) [?:?]
    
    
    
    

java.lang.IllegalArgumentException: plugin is not registered
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
    at com.velocitypowered.proxy.scheduler.VelocityScheduler.buildTask(VelocityScheduler.java:70) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
    at com.danifoldi.protogui.platform.velocity.ProtoGui$5.setup(ProtoGui.java:384) ~[?:?]
    at com.danifoldi.protogui.main.ProtoGuiLoader.load(ProtoGuiLoader.java:107) ~[?:?]
    at com.danifoldi.protogui.platform.velocity.ProtoGui.onShutdown(ProtoGui.java:105) ~[?:?]
    at com.danifoldi.protogui.platform.velocity.Lmbda$23.execute(Unknown Source) ~[?:?]
    at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
    at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
    at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) [?:?]
 
[07:36:27] [main/ERROR]: An error occurred while trying to perform tab completion.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to provide suggestions for proto for com.velocitypowered.proxy.console.VelocityConsole@71a46ea8
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
Expand
message.txt
13 KB
your plugin is very broken
﻿
[07:36:27] [main/ERROR]: An error occurred while trying to perform tab completion.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to provide suggestions for proto for com.velocitypowered.proxy.console.VelocityConsole@71a46ea8
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at com.velocitypowered.proxy.command.VelocityCommandManager.offerSuggestions(VelocityCommandManager.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.console.VelocityConsole.lambda$buildReader$2(VelocityConsole.java:111) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4147) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4060) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3630) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:603) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
Caused by: java.lang.RuntimeException: Unable to provide suggestions for proto for com.velocitypowered.proxy.console.VelocityConsole@71a46ea8
	at com.velocitypowered.proxy.command.VelocityCommandManager.offerBrigadierSuggestions(VelocityCommandManager.java:283) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.offerSuggestions(VelocityCommandManager.java:261) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	... 9 more
Caused by: java.lang.NullPointerException: permission
	at me.lucko.luckperms.common.treeview.PermissionRegistry.offer(PermissionRegistry.java:72) ~[?:?]
	at me.lucko.luckperms.velocity.listeners.MonitoringPermissionCheckListener$MonitoredPermissionFunction.getPermissionValue(MonitoringPermissionCheckListener.java:95) ~[?:?]
	at com.velocitypowered.proxy.console.VelocityConsole.getPermissionValue(VelocityConsole.java:76) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.api.permission.PermissionSubject.hasPermission(PermissionSubject.java:25) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.danifoldi.protogui.platform.velocity.CommandWrapper.hasPermission(CommandWrapper.java:84) ~[?:?]
	at com.danifoldi.protogui.platform.velocity.CommandWrapper.hasPermission(CommandWrapper.java:17) ~[?:?]
	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$0(InvocableCommandRegistrar.java:77) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$2(InvocableCommandRegistrar.java:95) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:84) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.SuggestionsProvider.provideAliasSuggestions(SuggestionsProvider.java:170) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.SuggestionsProvider.provideSuggestions(SuggestionsProvider.java:113) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.SuggestionsProvider.provideSuggestions(SuggestionsProvider.java:84) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.offerBrigadierSuggestions(VelocityCommandManager.java:280) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.offerSuggestions(VelocityCommandManager.java:261) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	... 9 more
[07:36:28] [main/ERROR]: An error occurred while trying to perform tab completion.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to provide suggestions for proto for com.velocitypowered.proxy.console.VelocityConsole@71a46ea8
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at com.velocitypowered.proxy.command.VelocityCommandManager.offerSuggestions(VelocityCommandManager.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.console.VelocityConsole.lambda$buildReader$2(VelocityConsole.java:111) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4147) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4060) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3630) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:603) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
Caused by: java.lang.RuntimeException: Unable to provide suggestions for proto for com.velocitypowered.proxy.console.VelocityConsole@71a46ea8
	at com.velocitypowered.proxy.command.VelocityCommandManager.offerBrigadierSuggestions(VelocityCommandManager.java:283) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.offerSuggestions(VelocityCommandManager.java:261) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	... 9 more
Caused by: java.lang.NullPointerException: permission
	at me.lucko.luckperms.common.treeview.PermissionRegistry.offer(PermissionRegistry.java:72) ~[?:?]
	at me.lucko.luckperms.velocity.listeners.MonitoringPermissionCheckListener$MonitoredPermissionFunction.getPermissionValue(MonitoringPermissionCheckListener.java:95) ~[?:?]
	at com.velocitypowered.proxy.console.VelocityConsole.getPermissionValue(VelocityConsole.java:76) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.api.permission.PermissionSubject.hasPermission(PermissionSubject.java:25) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.danifoldi.protogui.platform.velocity.CommandWrapper.hasPermission(CommandWrapper.java:84) ~[?:?]
	at com.danifoldi.protogui.platform.velocity.CommandWrapper.hasPermission(CommandWrapper.java:17) ~[?:?]
	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$0(InvocableCommandRegistrar.java:77) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$2(InvocableCommandRegistrar.java:95) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:84) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.SuggestionsProvider.provideAliasSuggestions(SuggestionsProvider.java:170) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.SuggestionsProvider.provideSuggestions(SuggestionsProvider.java:113) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.SuggestionsProvider.provideSuggestions(SuggestionsProvider.java:84) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.offerBrigadierSuggestions(VelocityCommandManager.java:280) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.offerSuggestions(VelocityCommandManager.java:261) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	... 9 more
[07:36:32] [main/ERROR]: An error occurred while running this command.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command protogui for com.velocitypowered.proxy.console.VelocityConsole@71a46ea8
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command protogui for com.velocitypowered.proxy.console.VelocityConsole@71a46ea8
	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:223) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:237) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 4 more
Caused by: java.lang.NullPointerException: permission
	at me.lucko.luckperms.common.treeview.PermissionRegistry.offer(PermissionRegistry.java:72) ~[?:?]
	at me.lucko.luckperms.velocity.listeners.MonitoringPermissionCheckListener$MonitoredPermissionFunction.getPermissionValue(MonitoringPermissionCheckListener.java:95) ~[?:?]
	at com.velocitypowered.proxy.console.VelocityConsole.getPermissionValue(VelocityConsole.java:76) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.api.permission.PermissionSubject.hasPermission(PermissionSubject.java:25) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.danifoldi.protogui.platform.velocity.CommandWrapper.hasPermission(CommandWrapper.java:84) ~[?:?]
	at com.danifoldi.protogui.platform.velocity.CommandWrapper.hasPermission(CommandWrapper.java:17) ~[?:?]
	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$0(InvocableCommandRegistrar.java:77) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$2(InvocableCommandRegistrar.java:95) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:84) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:404) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:315) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.parse(VelocityCommandManager.java:298) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:209) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:237) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]

**Comment by DaniFoldi** [comment]
Thanks for the input @KairuByte, I'll close the issue then.
